#####################################################################################
## Author: Jenny Sjaarda
## Project: PSYMETAB_GWAS
##
## Time-stamp: <[randomized_IDs.r] by JS 2019-09-25 10:42:03 CEST>
##
## Description: randomize IDs for creating genomestudio project with new IDs generated by GPCR
##
##
## History:
##
#####################################################################################

### RUN ON CHUV COMPUTER

library(readxl)
library(dplyr)
setwd("L:/PCN/UBPC/ANALYSES_RECHERCHE/Jenny/PSYMETAB_GWAS/data")
ids <- read.csv("Eap0819_1t26_27to29corrected_7b9b.csv", header=T, skip=8)
dim(ids)
#2767   14
ids$Sample_ID2 <-  gsub(' ', '', ids$Sample_ID)

setwd("L:/PCN/UBPC/ANALYSES_RECHERCHE/Jenny/PSYMETAB_GWAS/")
new_ids <- read_excel("CodesGenGSA.xlsx")
dim(new_ids)
#2310    6

# Colnames definitions
## SampleID: master sample ID
## AdditionalCodedID: randomized code
## RecodedSample_ID: sample ID used in genotype analysis
## Code: alternate RecodedSample_ID (usually with letter and number in reverse order, for eg. AMB360 and 360AMB)
## Ethnie: ethnicity
## Sexe: sex

### Define new column with "_" removed from "RecodedSample_ID"
new_ids$RecodeSample_ID2 <-  gsub('_', '', new_ids$RecodeSample_ID)

##########################################################################################
### there are some participants which were genotyped twice under different IDs.
duplicate_SampleIDs <- new_ids[which(duplicated(new_ids$SampleID)),"SampleID"]

# # A tibble: 16 x 1
#    SampleID
#    <chr>
#  1 0430J
#  2 0372J
#  3 0144J
#  4 0691M
#  5 0454T
#  6 0196J
#  7 0156J
#  8 0445M
#  9 0122M
# 10 0405T
# 11 0609M
# 12 0043J
# 13 0135J
# 14 0469T
# 15 0687M
# 16 0166J

# For example, considering #2 in the table above:
new_ids[which(new_ids$SampleID=="0372J"),]

# # A tibble: 2 x 7
#   SampleID AdditionnalCodedId RecodeSample_ID CODE    Ethnie    Sexe  RecodeSample_ID2
#   <chr>    <chr>              <chr>           <chr>   <chr>     <chr> <chr>
# 1 0372J    PBAIFEMQ           AMB365          0365AMB caucasien F     AMB365
# 2 0372J    PBAIFEMQ           0372J           0372J   caucasien F     0372J

## So, participant with ID: 0372J, had one ID as "0372J" and another as "0365AMB"

##########################################################################################
### there is one participant which has been given two new randomized codes.
duplicate_RecodeSample_ID <- new_ids[which(duplicated(new_ids$RecodeSample_ID2)),"RecodeSample_ID2"]

# # A tibble: 1 x 1
#   RecodeSample_ID
#   <chr>
# 1 0430J

new_ids[which(new_ids$RecodeSample_ID2=="0430J"),]

# # A tibble: 2 x 7
#   SampleID AdditionnalCodedId RecodeSample_ID CODE  Ethnie  Sexe  RecodeSample_ID2
#   <chr>    <chr>              <chr>           <chr> <chr>   <chr> <chr>
# 1 0430J    SHIHOIBV           0430J           0430J inconnu M     0430J
# 2 0430J    KEATCXMS           0430J           0430J inconnu M     0430J

## remove second occurance of "0430J"
new_ids2 <- new_ids[which(!duplicated(new_ids$RecodeSample_ID2)),]

joint <- left_join(ids, new_ids2, by=c("Sample_ID2"= "RecodeSample_ID2"))
NA_rows <- which(is.na(joint$AdditionnalCodedId))

joint[NA_rows, "AdditionnalCodedId"] <- joint[NA_rows,"Sample_ID2"]

## all ids in list provided by Celine were genotyped
which(!new_ids2$RecodeSample_ID2 %in% ids$Sample_ID2)

original_cols <- colnames(ids)[-length(colnames(ids))]

gs_sample_set <- joint
duplicate_newIDs <- which(duplicated(gs_sample_set$AdditionnalCodedId))
gs_sample_set[duplicate_newIDs, "AdditionnalCodedId"] <- paste0(gs_sample_set[duplicate_newIDs, "AdditionnalCodedId"],"002")
gs_sample_set[, "Sample_ID"] <- gs_sample_set[, "AdditionnalCodedId"]
gs_sample_set[, "Sample_Name"] <- gs_sample_set[, "AdditionnalCodedId"]

matched_codes <- gs_sample_set[,c("Sample_ID2","AdditionnalCodedId")]
colnames(matched_codes) <- c("sampleID", "randomizedID")

gs_sample_set <- joint[,original_cols]



setwd("L:/PCN/UBPC/ANALYSES_RECHERCHE/Jenny/PSYMETAB_GWAS/data")
write.table(gs_sample_set, "Eap0819_1t26_27to29corrected_7b9b_randomizedID.csv", sep=",", row.names=F, col.names=F, quote=F,na="")
setwd("L:/PCN/UBPC/ANALYSES_RECHERCHE/Jenny/PSYMETAB_GWAS/")
write.table(matched_codes, "ID_key.csv", sep=",", row.names=F, col.names=T, quote=F,na="")

## Manually copy the header to the new csv

# [Header],,,,,,,,,,,,,
# Investigator Name,,,,,,,,,,,,,
# Project Name,,,,,,,,,,,,,
# Experiment Name,,,,,,,,,,,,,
# Date,,,,,,,,,,,,,
# [Manifests],,,,,,,,,,,,,
# A,GSA_UPPC_20023490X357589_A1,,,,,,,,,,,,
# [Data],,,,,,,,,,,,,

## Transfer "ID_key.csv", "Eap0819_1t26_27to29corrected_7b9b_randomizedID.csv",
## and "Eap0819_1t26_27to29corrected_7b9b.csv" to the server using FileZilla
q()
n
