---
title: "About"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Describe your project.

see `data/README.md` for information on data inputs
see `scripst/README.md` for information on scripts

*  [INFO](info.html)

---
title: "Home"
---

**Last updated:** `r Sys.Date()`

**Code version:** `r system("git log -1 --format='%H'", intern = TRUE)`

We used this site to collaborate and share our results.
Please feel free to explore.

# Introduction

- Antipsychotic induced weight gain is a common side effect of antipsychotic treatement. 
- However, this observation varies considerably across patients, and has been shown to be linked to many factors, including type of treatment, pre-treatment body mass index (BMI), sex and age. 
- Beyond these variables, significant variability across individuals remains, pointing to a potential role of inter-individual genetic variability in antipsychotic induce weight gain. 
- Indeed, the heritability (h2) for antipsychotic induced weight gain has been estimated to be 0.8 (Theisen et al., 2005). 
- Despite these observations, few genome-wide significant loci have been discovered. Identification of genetic polymorphisms responsible for antipsychotic induced weight gain is a valuable research endeavor which could lead to both improved treatment and more personalized interventions to combat this harmful and debilitating side-effect of antipsychotics and improve quality of life.

# Methods 

- In this study, we sought to identify novel genetic polymorphisms for antipsychotic induced weight gain across a range of antipsychotic treatments. 
- These treatments included olanzapine, clozapine, valproate, quetiapine, risperidone, amisulpride, among others. 
- The study population included 2767 psychiatric participants who have been followed up to XX years with up to XX number of visits, and under at least one antipsychotic treatment at each visit. 
- Standard clinical measures were assessed and recorded at each visit, including weight-gain, to evaluate the evolution of BMI overtime. 
- All participants were genotyped on the Global Screening Array (GSA) v2 with multiple disease option (MD) chip. 
- After standard quality control filters (i.e. missingness, sex check, excess relatedness, minor allele frequency and Hardy-Weinberg) and imputation were performed, our study sample consisted of 2647 samples and 10382351 SNPs. 
- We chose to limit the analyses to only the European subset comprising 2116 samples. 
- European ancestry was determined using snpweights, a software for inferring genome-wide genetic ancestry using SNP weights precomputed from large external reference panels (Chen et al., 2013). 
- We analyzed drugs both separately and combined (based on mode of action and biological pathways). 
- Additionally, we investigated the evolution of BMI using various definitions, including delta change in BMI over time, slope of BMI over time (estimated using a linear model with BMI regressed on time between follow-up visits, in days), and weighted slope of BMI over time (weighted by the inverse SE). 
- These definitions were then repeated restricting to only 6, 3 and 1 month of follow-up, as weight gain has been shown to be greatest in the first 6 months and plateau with continual antipsychotic use. 
- We also utilized the UKBiobnak (UKB), a very large population-based cohort, as a control population. Briefly, we included 31056 participants with at least two measures for BMI and performed a GWAS with the change in BMI over time (as in the psychiatric cohort) as the dependent phenotype. 
- Analyses were restricted to British individuals. These results served as a control GWAS to ensure that GW-significant findings within the psychiatric cohort, truly represent antipsychotic-induced weight gain-associated loci as apposed weight gain-associated loci, in general. 

# Results 

- In summary, we identified 15 loci showing a GW-significant difference between the UKBB and our psychiatric cohort for four different antipsychotic drugs (olanzapine, clozapine, risperidone, and amisulpride) whereby a stronger (p < 5e-06) association was identified between these loci and BMI slope in the psychiatric cohort compared to the general population in the UKBB. 
- These results suggest that these loci may represent a weight-inducing effect specific to antipsychotic use rather than some wide-ranging mechanism present in the general population. 

# Discussion

- Future analyses will seek to replicate these findings in a larger cohort, compare these findings to a GWAS of BMI in both the general population (using the GIANT consortium, for example) and within our psychiatric cohort, and finally expand the phenotypes of interest to biomarker levels including LDL, HDL, creatine, and glucose levels. 

Here are some useful links:



