---
title: GWAS summary"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
---

**The following document outlines and summarizes the GWAS performed in PSYMETAB.**

## Overview of analyses

### 1. Initial GWAS.
- Initially, three GWAS were performed (see [GWAS method](GWAS_method.html) and [GWAS results](GWAS_method.html) for more details):
  (a) Baseline GWAS: standard GWAS with miscellaneous baseline variables using first round of follow-up (eg. LDL, HDL, BMI, etc.).
  (b) Interaction GWAS: to test gene*drug interaction on the evolution of BMI to identify SNPs which interact with psychiatric drug use to cause an increase in BMI.
  (c) Subgroup GWAS: to test GWAS of evolution of BMI in those under a certain drug vs those not under that drug (i.e. two distinct subgroups for each drug of interest: cases and controls).
- Analayses (b) and (c) are very similar, where a SNP association which differs significantly between the two subgroups in (c) (using a heterogeneity test for example) would suggest that this SNP acts through the drug to exert its effect on BMI.

### 2. Comparison with UKBB as control population.
- Ideally, analyses (b) and/or (c) above would idenitfy SNPs that are linked to increase in BMI through an interaction with drug use.
- However, due to the nature of the PSYMETAB study design, all participants are taking some (or multiple) drugs and have some pre-existing psychiatric condition.
- Therefore, there are no *true* controls (i.e. the control population we were using was not ideal because they are all taking another drug that could confound the analysis and have some psychiatric disease).
- Indeed, after performing these analyses, no striking associations were identified.
- It was then decided to use the UKBB as our control population.
- Specifically, the subset of UKBB participants with more than two measures for BMI to identify SNPs linked to change (slope) of BMI and compare these signals with those identified in PSYMETAB.
- For further details and results see [GWAS UKBB control](GWAS_UKBB_control.html).

### 3. Replication in UKBB.
- Using the drug-use variable in the UKBB, we sought to replicate the drug-specific signals we identified in PSYMETAB (i.e. the significant results from the subgroup under a given drug, described above).
- Subgroups were created in UKBB based on drug use.
- Because the number of participants in the UKBB with both multiple measures for BMI **and** under a psychiatric of interest is very small, BMI itself was used as a proxy for evolution of BMI.
- For more details see: [GWAS UKBB replication](GWAS_UKBB_replication.html).

### 4. Case-only analysis.
- There was also interest to identify SNPs linked to an evolution of BMI in the general psychiatric population (i.e. all PSYMETAB regardless of which drug being taken).
- Signals identified in this analysis would be indictative of one of three relationships:
  (a) SNPs linked to BMI change in general (not specific to the psychiatric population).
  (b) SNPs linked to BMI change in the psychiatric population (i.e. are not important in the general, non-psychiatric population, interact somehow with disease status).
  (c) SNPs which act through psychiatric drugs generally speaking but not one drug individually.
- Impossible for us to distinguish between (a) and (c) but we can test if SNPs are associated with BMI change in the UKBB to rule out/in (b).
- To perform this analysis, the PSYMETAB population was divided into distinct subgroups and results were then meta-analyzed.
- For more details see: [GWAS case only](GWAS_case_only.html).
- Motivatation for 1(c) was to optimize sample size, whereas in analysis #4, distinct subgroups were created which allows for a straight forward meta-analysis across groups, in an effort to identify signals within the full popualtion.
